In [1]:
import numpy as np

In [2]:
# Create a 1D numpy array
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [3]:
# Type of the array
type(arr)

numpy.ndarray

In [4]:
# Shape of the array
arr.shape

(5,)

In [5]:
arr2 = np.array([1,2,3,4,5,6,7,8,9,10])
arr2.reshape(1,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [6]:
arr2.shape

(10,)

In [7]:
arr2.reshape(10,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [8]:
arr2 = np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [9]:
arr2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr2.shape

(3, 4)

In [11]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
# Attributes of an array
arr = np.array([[1,2,3,4],[5,6,7,8]])

print("Array:\n", arr)
print("Shape:", arr.shape)
print("Data type:", arr.dtype)
print("Number of dimensions:", arr.ndim)
print("Total number of elements:", arr.size)
print("Length of one array element in bytes:", arr.itemsize)
print("Total bytes consumed by the elements of the array:", arr.nbytes)

Array:
 [[1 2 3 4]
 [5 6 7 8]]
Shape: (2, 4)
Data type: int64
Number of dimensions: 2
Total number of elements: 8
Length of one array element in bytes: 8
Total bytes consumed by the elements of the array: 64


In [18]:
# Numpy Vectorized Operations
arr1 = np.array([1,2,3,4])
arr2 = np.array([10,20,30,40])

# Elementwise addition
print(arr1 + arr2)

# Elementwise subtraction
print(arr1 - arr2)

# Elementwise multiplication
print(arr1 * arr2)

# Elementwise division
print(arr1/arr2)

[11 22 33 44]
[ -9 -18 -27 -36]
[ 10  40  90 160]
[0.1 0.1 0.1 0.1]


In [19]:
# Universal Functions
arr = np.array([1, 2, 3, 4, 5])

# Square root of each element
print(np.sqrt(arr))

# Exponential of each element
print(np.exp(arr))

# Power of 3 of each element
print(np.power(arr, 3))

# Logarithm of each element
print(np.log(arr))

# Trigonometric functions
print(np.sin(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[  1   8  27  64 125]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [20]:
# Aggregate Functions
arr = np.array([[1,2,3,4],[5,6,7,8]])

# Sum of all elements
print(np.sum(arr))

# Sum of each column
print(np.sum(arr, axis=0))

# Sum of each row
print(np.sum(arr, axis=1))

# Minimum of all elements
print(np.min(arr))

# Minimum of each column
print(np.min(arr, axis=0))

# Minimum of each row
print(np.min(arr, axis=1))

# Maximum of all elements
print(np.max(arr))

36
[ 6  8 10 12]
[10 26]
1
[1 2 3 4]
[1 5]
8


In [21]:
# Array Slicing and Indexing
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [24]:
print(arr[0][0])

1


In [26]:
print(arr[2][3])

12


In [27]:
print(arr[1:,2:])

[[ 7  8]
 [11 12]]


In [28]:
print(arr[1:])

[[ 5  6  7  8]
 [ 9 10 11 12]]


In [29]:
arr[1:] = 100
print(arr)

[[  1   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [31]:
# Normalizing an array
arr = np.random.randint(0, 100, (3, 4))
print(arr)
print("\n")
arr_min, arr_max = arr.min(), arr.max()
arr = (arr - arr_min)/(arr_max - arr_min)
print(arr)

[[64 28 76 14]
 [97 39 62  3]
 [76 22 65 67]]


[[0.64893617 0.26595745 0.77659574 0.11702128]
 [1.         0.38297872 0.62765957 0.        ]
 [0.77659574 0.20212766 0.65957447 0.68085106]]
